# Generated by Django 4.2.7 on 2026-02-28 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AgenciaBimbo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_agente",
                    models.IntegerField(
                        help_text="FK lógica a conf_empresas.id",
                        unique=True,
                        verbose_name="ID Agente SIDIS",
                    ),
                ),
                (
                    "Nombre",
                    models.CharField(max_length=255, verbose_name="Nombre Agencia"),
                ),
                (
                    "db_powerbi",
                    models.CharField(
                        blank=True,
                        help_text="Nombre de la base de datos PowerBI del agente (de conf_empresas.name)",
                        max_length=150,
                        null=True,
                        verbose_name="BD PowerBI",
                    ),
                ),
                (
                    "nbOficinaV",
                    models.CharField(
                        default="1001", max_length=10, verbose_name="Oficina Ventas"
                    ),
                ),
                (
                    "SIDIS",
                    models.CharField(default="SI", max_length=10, verbose_name="SIDIS"),
                ),
                (
                    "nmOficinaV",
                    models.CharField(
                        default="BIMBO", max_length=50, verbose_name="Nombre Oficina"
                    ),
                ),
                (
                    "CEVE",
                    models.IntegerField(
                        default=0,
                        help_text="Código CEVE asignado por BIMBO",
                        verbose_name="Código CEVE",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("ACTIVO", "Activo"),
                            ("INACTIVO", "Inactivo"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "es_bimbo",
                    models.BooleanField(
                        default=True,
                        help_text="Marca si la agencia opera con BIMBO",
                        verbose_name="Es BIMBO",
                    ),
                ),
                (
                    "id_proveedor_bimbo",
                    models.CharField(
                        blank=True,
                        help_text="idProveedor BIMBO en el SIDIS de esta agencia (resultado de Discovery)",
                        max_length=10,
                        null=True,
                        verbose_name="ID Proveedor BIMBO",
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Alta"
                    ),
                ),
                (
                    "fecha_ultimo_snapshot",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Snapshot"
                    ),
                ),
            ],
            options={
                "verbose_name": "Agencia BIMBO",
                "verbose_name_plural": "Agencias BIMBO",
                "db_table": "agencias_bimbo",
                "ordering": ["CEVE"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PermisoBimboAgente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agencia_id",
                    models.IntegerField(
                        help_text="FK lógica a AgenciaBimbo.id (powerbi_bimbo.agencias_bimbo)",
                        verbose_name="ID Agencia",
                    ),
                ),
                (
                    "puede_ejecutar",
                    models.BooleanField(
                        default=False,
                        help_text="Permite ejecutar Discovery, Snapshot y Homologación",
                        verbose_name="Puede Ejecutar",
                    ),
                ),
                (
                    "puede_editar",
                    models.BooleanField(
                        default=False,
                        help_text="Permite hacer match manual en equivalencias",
                        verbose_name="Puede Editar",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permisos_bimbo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permiso Agente BIMBO",
                "verbose_name_plural": "Permisos Agentes BIMBO",
                "db_table": "bimbo_permiso_agente",
                "managed": True,
                "unique_together": {("user", "agencia_id")},
            },
        ),
    ]
