# Generated by Django 4.2.7 on 2026-03-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permisos", "0015_confempresas_es_bimbo"),
    ]

    operations = [
        migrations.AddField(
            model_name="confempresas",
            name="ceve",
            field=models.IntegerField(
                blank=True,
                help_text="Código CEVE asignado si es agencia BIMBO",
                null=True,
                verbose_name="Código CEVE",
            ),
        ),
    ]
