# Generated by Django 5.2.9 on 2026-03-19 18:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permisos", "0019_add_email_reportes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfCdtProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre legible del proveedor (ej: MasterFoods Colombia)",
                        max_length=100,
                        verbose_name="Nombre Proveedor",
                    ),
                ),
                (
                    "codigo_proveedor",
                    models.CharField(
                        help_text="Código usado para filtrar en cuboventas (ej: 006-MASTERFOODS COLOMBIA LTDA)",
                        max_length=100,
                        verbose_name="Código Proveedor",
                    ),
                ),
                (
                    "codigos_distribuidor",
                    models.TextField(
                        help_text='JSON con códigos de distribuidor. Ejemplo: [{"codigo": "17645695", "empresa": "Distrijass", "tipo": "con_vendedores"}, {"codigo": "10359935", "empresa": "Distrijass", "tipo": "sin_vendedores"}]',
                        verbose_name="Códigos Distribuidor",
                    ),
                ),
                (
                    "vendedores_especiales",
                    models.CharField(
                        blank=True,
                        help_text="Vendedores especiales separados por coma (ej: MA01,MA02,M1013,EMA01,EMA03)",
                        max_length=200,
                        null=True,
                        verbose_name="Vendedores Especiales",
                    ),
                ),
                (
                    "bodega_especial",
                    models.CharField(
                        blank=True,
                        help_text="Patrón de bodega especial para filtro de inventario (ej: SPT)",
                        max_length=100,
                        null=True,
                        verbose_name="Patrón Bodega Especial",
                    ),
                ),
                (
                    "sftp_host",
                    models.CharField(
                        help_text="Servidor SFTP (ej: mars.cdtbigdata.com)",
                        max_length=200,
                        verbose_name="SFTP Host",
                    ),
                ),
                (
                    "sftp_port",
                    models.IntegerField(default=22, verbose_name="SFTP Puerto"),
                ),
                (
                    "sftp_user",
                    models.CharField(max_length=100, verbose_name="SFTP Usuario"),
                ),
                (
                    "sftp_pass",
                    models.CharField(max_length=200, verbose_name="SFTP Contraseña"),
                ),
                (
                    "sftp_ruta_remota",
                    models.CharField(
                        default="/",
                        help_text="Directorio remoto donde se depositan los archivos",
                        max_length=200,
                        verbose_name="Ruta Remota SFTP",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Proveedor CDT",
                "verbose_name_plural": "Proveedores CDT",
                "db_table": "conf_cdt_proveedor",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="permisosbarra",
            options={
                "managed": False,
                "permissions": (
                    ("nav_bar", "Ver la barra de menú"),
                    ("panel_cubo", "Panel de cubo"),
                    ("panel_bi", "Panel de BI"),
                    ("panel_actualizacion", "Panel de Actualización de datos"),
                    ("panel_interface", "Panel de Interfaces Contables"),
                    ("cubo", "Generar cubo de ventas"),
                    ("proveedor", "Generar cubo de ventas para proveedor"),
                    ("matrix", "Generar Matrix de Ventas"),
                    ("interface", "Generar interface contable"),
                    ("interface_siigo", "Generar interface Siigo"),
                    ("plano", "Generar archivo plano"),
                    ("cargue_plano", "Cargar archivo plano"),
                    ("cargue_tsol", "Cargue archivo plano TSOL"),
                    ("informe_bi", "Informe BI"),
                    ("informe_bi_embed", "Informe BI Embed"),
                    ("actualizar_base", "Actualización de datos"),
                    ("actualizacion_bi", "Actualizar BI"),
                    ("admin", "Ir al Administrador"),
                    ("amovildesk", "Puede ver Informe Amovildesk"),
                    ("reportes", "Puede ver Reportes"),
                    (
                        "reportes_bimbo",
                        "Puede ver Reportes Bimbo (Venta Cero, Ruteros)",
                    ),
                    ("reporte_preventa_bimbo", "Puede ver Reporte Preventa Bimbo"),
                    ("cargue_infoventas", "Cargar Archivo Infoventas"),
                    ("cargue_maestras", "Cargar Tablas Maestras"),
                    ("cargue_infoproducto", "Cargar Información de Producto"),
                    ("cargue_infoproveedor", "Cargar Información de Proveedor"),
                    ("faltantes", "Generar informe de Faltantes"),
                    ("preventa", "Generar informe de Preventa"),
                    ("trazabilidad", "Generar informe de Trazabilidad Preventa"),
                    (
                        "config_email_reportes",
                        "Configurar correos para reportes programados",
                    ),
                ),
                "verbose_name": "Permiso",
                "verbose_name_plural": "Permisos",
            },
        ),
        migrations.AddField(
            model_name="confempresas",
            name="planos_cdt",
            field=models.CharField(
                blank=True,
                help_text="Lista de IDs de conf_sql_cdt (ej: [1,2,3])",
                max_length=200,
                null=True,
                verbose_name="Planos CDT (IDs)",
            ),
        ),
        migrations.AddField(
            model_name="confempresas",
            name="proveedor_cdt",
            field=models.ForeignKey(
                blank=True,
                help_text="Proveedor CDT asociado a esta empresa (ej: MasterFoods)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="permisos.confcdtproveedor",
                verbose_name="Proveedor CDT",
            ),
        ),
        migrations.CreateModel(
            name="ConfSqlCdt",
            fields=[
                (
                    "nbSql",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "El ID debe ser un número positivo"
                            )
                        ],
                        verbose_name="ID",
                    ),
                ),
                (
                    "nmReporte",
                    models.CharField(
                        help_text="Nombre identificador del reporte CDT (ej: ventas_cdt, clientes_cdt)",
                        max_length=100,
                        verbose_name="Nombre del Reporte",
                    ),
                ),
                (
                    "txTabla",
                    models.CharField(
                        blank=True,
                        help_text="Tabla de donde se extraen los datos (ej: cuboventas, clientes, inventario)",
                        max_length=100,
                        null=True,
                        verbose_name="Tabla Fuente",
                    ),
                ),
                (
                    "txDescripcion",
                    models.CharField(
                        blank=True,
                        help_text="Descripción del propósito de esta consulta CDT",
                        max_length=255,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "txSqlExtrae",
                    models.TextField(
                        blank=True,
                        help_text="Query SQL con parámetros :fi (fecha inicio), :ff (fecha fin), :IdDs (empresa)",
                        null=True,
                        verbose_name="SQL de Extracción",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name": "Config SQL CDT",
                "verbose_name_plural": "Config SQL CDT",
                "db_table": "conf_sql_cdt",
                "ordering": ["nbSql"],
                "indexes": [
                    models.Index(fields=["nmReporte"], name="sqlcdt_nmreporte_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="CdtEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha Inicio Periodo")),
                ("fecha_fin", models.DateField(verbose_name="Fecha Fin Periodo")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("procesando", "Procesando"),
                            ("enviado", "Enviado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_ventas",
                    models.IntegerField(default=0, verbose_name="Total Ventas"),
                ),
                (
                    "total_clientes",
                    models.IntegerField(default=0, verbose_name="Total Clientes"),
                ),
                (
                    "total_inventario",
                    models.IntegerField(default=0, verbose_name="Total Inventario"),
                ),
                (
                    "archivos_generados",
                    models.TextField(
                        blank=True,
                        help_text="JSON con lista de archivos generados y sus tamaños",
                        null=True,
                        verbose_name="Archivos Generados",
                    ),
                ),
                (
                    "archivo_descarga",
                    models.CharField(
                        blank=True,
                        help_text="Ruta al archivo ZIP para descarga",
                        max_length=500,
                        null=True,
                        verbose_name="Archivo Descarga",
                    ),
                ),
                (
                    "enviado_sftp",
                    models.BooleanField(default=False, verbose_name="Enviado por SFTP"),
                ),
                (
                    "log_ejecucion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Log de Ejecución"
                    ),
                ),
                (
                    "fecha_ejecucion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Ejecución"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios_cdt",
                        to="permisos.confempresas",
                        verbose_name="Empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="envios",
                        to="permisos.confcdtproveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Envío CDT",
                "verbose_name_plural": "Envíos CDT",
                "db_table": "cdt_envio",
                "ordering": ["-fecha_ejecucion"],
                "permissions": [
                    ("ejecutar_cdt", "Puede ejecutar generación de planos CDT"),
                    ("reenviar_cdt", "Puede re-enviar planos CDT por SFTP"),
                ],
                "indexes": [
                    models.Index(fields=["estado"], name="cdtenvio_estado_idx"),
                    models.Index(
                        fields=["fecha_inicio", "fecha_fin"],
                        name="cdtenvio_periodo_idx",
                    ),
                ],
            },
        ),
    ]
