# Generated by Django 5.2.9 on 2026-03-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permisos", "0020_confcdtproveedor_alter_permisosbarra_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confempresas",
            name="envio_cdt_activo",
            field=models.BooleanField(
                default=False,
                help_text="Habilita el envío nocturno automático de planos CDT para esta empresa",
                verbose_name="Envío CDT activo",
            ),
        ),
    ]
