# Generated by Django 5.2.9 on 2026-03-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permisos", "0021_confempresas_envio_cdt_activo"),
        ("permisos", "0021_tsol_models"),
    ]

    operations = []
