# Generated by Django 5.2.9 on 2026-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permisos", "0022_merge_20260319_1556"),
    ]

    operations = [
        migrations.AddField(
            model_name="confempresas",
            name="sftp_cdt_host",
            field=models.CharField(
                blank=True,
                help_text="Servidor SFTP para esta empresa (ej: mars.cdtbigdata.com)",
                max_length=200,
                null=True,
                verbose_name="SFTP Host CDT",
            ),
        ),
        migrations.AddField(
            model_name="confempresas",
            name="sftp_cdt_pass",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="SFTP Contraseña CDT",
            ),
        ),
        migrations.AddField(
            model_name="confempresas",
            name="sftp_cdt_port",
            field=models.IntegerField(
                blank=True, default=22, null=True, verbose_name="SFTP Puerto CDT"
            ),
        ),
        migrations.AddField(
            model_name="confempresas",
            name="sftp_cdt_ruta_remota",
            field=models.CharField(
                blank=True,
                default="/",
                help_text="Directorio remoto donde se depositan los archivos",
                max_length=200,
                null=True,
                verbose_name="Ruta Remota SFTP CDT",
            ),
        ),
        migrations.AddField(
            model_name="confempresas",
            name="sftp_cdt_user",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="SFTP Usuario CDT"
            ),
        ),
    ]
