# Generated by Django 4.2.7 on 2026-03-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permisos", "0026_consolidate_providers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="confempresas",
            name="cdt_bodega_especial",
            field=models.CharField(
                blank=True,
                help_text="Patrón de bodega especial para filtro de inventario (ej: SPT)",
                max_length=100,
                null=True,
                verbose_name="Patrón Bodega Especial CDT",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="cdt_codigo_proveedor",
            field=models.CharField(
                blank=True,
                help_text="Código para filtrar en cuboventas (ej: 006-MASTERFOODS COLOMBIA LTDA)",
                max_length=100,
                null=True,
                verbose_name="Código Proveedor CDT",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="cdt_codigos_distribuidor",
            field=models.TextField(
                blank=True,
                help_text='JSON con códigos de distribuidor. Ejemplo: [{"codigo": "17645695", "empresa": "Distrijass", "tipo": "con_vendedores"}]',
                null=True,
                verbose_name="Códigos Distribuidor CDT",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="cdt_conexion",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='JSON: {"host": "", "port": 22, "user": "", "pass": "", "ruta_remota": "/"}',
                null=True,
                verbose_name="Conexión SFTP CDT",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="cdt_nombre_proveedor",
            field=models.CharField(
                blank=True,
                help_text="Nombre del proveedor CDT (ej: MasterFoods Colombia)",
                max_length=100,
                null=True,
                verbose_name="Nombre Proveedor CDT",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="cdt_vendedores_especiales",
            field=models.CharField(
                blank=True,
                help_text="Vendedores especiales separados por coma (ej: MA01,MA02)",
                max_length=200,
                null=True,
                verbose_name="Vendedores Especiales CDT",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="cosmos_conexion",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='JSON: {"host": "", "port": 990, "user": "", "pass": "", "ruta_remota": "/", "certificate": ""}',
                null=True,
                verbose_name="Conexión FTPS Cosmos",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="tsol_bodega_to_code",
            field=models.TextField(
                blank=True,
                help_text='JSON dict bodega→código. Ej: {"CALI":"01","PALMIRA":"01"}',
                null=True,
                verbose_name="Mapeo Bodega→Código TSOL",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="tsol_code_to_sede",
            field=models.TextField(
                blank=True,
                help_text='JSON dict código→nombre. Ej: {"01":"PALMIRA/CALI","02":"TULUÁ"}',
                null=True,
                verbose_name="Mapeo Código→Sede TSOL",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="tsol_codigo",
            field=models.CharField(
                blank=True,
                help_text="Código para nombre del ZIP (ej: DISTRIJASS_211688)",
                max_length=100,
                null=True,
                verbose_name="Código TSOL",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="tsol_conexion",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='JSON: {"host": "", "port": 21, "user": "", "pass": "", "ruta_remota": "/"}',
                null=True,
                verbose_name="Conexión FTP TSOL",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="tsol_filtro_proveedores",
            field=models.TextField(
                blank=True,
                help_text='JSON array de proveedores para filtrar. Ej: ["023-COLGATE","024-PAPELES"]',
                null=True,
                verbose_name="Filtro Proveedores TSOL",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="tsol_nombre",
            field=models.CharField(
                blank=True,
                help_text="Nombre legible (ej: Distrijass Cali)",
                max_length=100,
                null=True,
                verbose_name="Nombre TSOL",
            ),
        ),
        migrations.AlterField(
            model_name="confempresas",
            name="tsol_sedes_permitidas",
            field=models.CharField(
                blank=True,
                help_text="Códigos separados por coma (ej: 01,04,06). Vacío = todas.",
                max_length=200,
                null=True,
                verbose_name="Sedes Permitidas TSOL",
            ),
        ),
        migrations.AlterField(
            model_name="cosmosenvio",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
